version: '2.4'

services:
  postgres:
    container_name: postgres
    image: index.docker.io/postgres:11-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    restart: "no"

volumes:
  postgresdata:

networks:
  default: